<?php

/**
 * @file
 * This file defines all the necessary hooks and functions to create
 * a Google Map Field field type and also a WYSIWYG editor plugin
 * for inserting maps directly into filtered content.
 */

/**
 * Implements hook_help().
 */
function google_map_field_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#google_map_field':
      $output = t('Add Google Map type fields to content types.');
  }
  return $output;
}

/**
 * Implements hook_permission().
 */
function google_map_field_permission() {
  return array(
    'access google map api key' => array(
      'title' => t('Access Google Map API Key'),
      'description' => t('Allow access to define/edit the Google Map API key for the Google Map Field module.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function google_map_field_init() {
  google_map_field_add_maps_api();
}

/**
 * Implements hook_menu().
 */
function google_map_field_menu() {
  $items = array();

  $items['admin/config/google-map-field-apikey'] = array(
    'title' => 'Google Map Field API Key',
    'description' => 'Set your Google Maps API key.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_map_field_apikey_settings_form'),
    'file' => 'includes/google_map_field.admin.inc',
    'access arguments' => array('access google map api key'),
  );

  return $items;
}

/**
 * Implements hook_field_info().
 */
function google_map_field_field_info() {
  return array(
    'google_map_field' => array(
      'label' => t('Google Map Field'),
      'description' => t('This field stores and renders Google Maps.'),
      'default_widget' => 'google_map_field_widget',
      'default_formatter' => 'google_map_field_formatter_default',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function google_map_field_field_widget_info() {
  return array(
    'google_map_field_widget' => array(
      'label' => t('Map'),
      'field types' => array('google_map_field'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function google_map_field_field_formatter_info() {
  $formats = array(
    'google_map_field_formatter_default' => array(
      'label' => t('Map'),
      'description' => t('Default display for Google map field.'),
      'field types' => array('google_map_field'),
    ),
    'google_map_field_formatter_wkt' => array(
      'label' => t('WKT'),
      'description' => t('Use WKT format to display the google maps point info'),
      'field types' => array('google_map_field'),
    ),
    'google_map_field_formatter_name' => array(
      'label' => t('Map Name'),
      'description' => t('Use Map Name format to display just the name of each map'),
      'field types' => array('google_map_field'),
    ),
  );
  return $formats;
}

/**
 * Implements hook_field_widget_error().
 */
function google_map_field_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element, $error['message']);
}

/**
 * Implements hook_field_is_empty().
 */
function google_map_field_field_is_empty($item, $field) {
  if (empty($item['lat']) || empty($item['lon'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_view().
 */
function google_map_field_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  drupal_add_css(drupal_get_path('module', 'google_map_field') . '/css/google_map_field.css');
  $element = array();

  switch ($display['type']) {
    case 'google_map_field_formatter_wkt':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => 'POINT(' . $item['lon'] . ' ' . $item['lat'] . ')');
      }
      break;
    case 'google_map_field_formatter_default':
      foreach ($items as $delta => $item) {
        $element[$delta] = google_map_field_format_field($item, $delta, $display);
      }
      break;
    case 'google_map_field_formatter_name':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => $item['name'] );
      }
      break;
  }

  return $element;
}

/**
 * This function formats the google map field for display,
 * called by google_map_field_field_formatter_view().
 */
function google_map_field_format_field($item, $delta, $display) {

  drupal_add_js(drupal_get_path('module', 'google_map_field') . '/js/google_map_field_node_display.js', 'file');

  $element = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('field-item')),
  );
  $element['google_map_field'] = array(
    'item' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('field-item'),
      ),
      'text' => array(
        '#markup' => theme('google_map_field', array(
          'name' => check_plain($item['name']),
          'lat' => $item['lat'],
          'lng' => $item['lon'],
          'zoom' => $item['zoom'],
        )),
      ),
    ),
  );

  return $element;
}

/**
 * Implements hook_field_widget_form().
 */
function google_map_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $element['#title'] = t('Define Location');
  $element['#description'] = '<p>' . t('To set a location for the map, click the "Set Map Marker" button, or enter the latitude/longitude in the field provided.') . '</p>';

  $element += array(
    '#type' => 'fieldset',
    '#collapsed' => FALSE,
    '#collapsible' => TRUE,
    '#attached' => array(
      'library' => array(
        array('system', 'ui.dialog'),
      ),
      'js' => array(
        drupal_get_path('module', 'google_map_field') . '/js/google_map_field_previews.js',
        drupal_get_path('module', 'google_map_field') . '/js/google_map_field_setter.js',
      ),
      'css' => array(
        drupal_get_path('module', 'google_map_field') . '/css/google_map_field.css',
      ),
    ),
  );

  if (isset($instance['default_value'][0])) {
    $name = isset($items[$delta]['name']) ? $items[$delta]['name'] : $instance['default_value'][0]['name'];
    $lat  = isset($items[$delta]['lat']) ? $items[$delta]['lat'] : $instance['default_value'][0]['lat'];
    $lng  = isset($items[$delta]['lon']) ? $items[$delta]['lon'] : $instance['default_value'][0]['lon'];
    $zoom = isset($items[$delta]['zoom']) ? $items[$delta]['zoom'] : $instance['default_value'][0]['zoom'];
  }
  else {
    $name = isset($items[$delta]['name']) ? $items[$delta]['name'] : NULL;
    $lat  = isset($items[$delta]['lat']) ? $items[$delta]['lat'] : NULL;
    $lng  = isset($items[$delta]['lon']) ? $items[$delta]['lon'] : NULL;
    $zoom = isset($items[$delta]['zoom']) ? $items[$delta]['zoom'] : NULL;
  }

  $element['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Map Name'),
    '#default_value' => $name,
    '#prefix' => '<div class="google-map-field-fields-container">',
    '#attributes' => array(
      'data-name-delta' => $delta,
    ),
  );
  $element['lat'] = array(
    '#type' => 'textfield',
    '#title' => t('Latitude'),
    '#required' => $instance['required'],
    '#element_validate' => array('google_map_field_latlon_validate'),
    '#default_value' => $lat,
    '#attributes' => array(
      'data-lat-delta' => $delta,
    ),
  );
  $element['lon'] = array(
    '#type' => 'textfield',
    '#title' => t('Longitude'),
    '#required' => $instance['required'],
    '#element_validate' => array('google_map_field_latlon_validate'),
    '#default_value' => $lng,
    '#attributes' => array(
      'data-lng-delta' => $delta,
    ),
  );
  $element['zoom'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom'),
    '#default_value' => $zoom,
    '#attributes' => array(
      'data-zoom-delta' => $delta,
    ),
    '#suffix' => '</div>',
  );
  $element['map_preview_' . $delta] = array(
    '#type' => 'container',
    '#prefix' => '<div class="google-map-field-setter-container">',
    '#suffix' => '<div><strong>' . t('Map Preview') . '</strong></div><div class="google-map-field-preview" date-field-name="' . $field['field_name'] . '" data-delta="' . $delta . '"></div>',
  );
  $element['open_map'] = array(
    '#type' => 'button',
    '#value' => t('Set Map Marker'),
    '#attributes' => array(
      'data-delta' => $delta,
      'id' => 'map_setter_' . $delta,
      'data-field-name' => $field['field_name'],
    ),
    '#suffix' => '</div><div style="clear: both;"></div>',
  );

  return $element;
}

/**
 * Custom validation function for latitude/longitude fields.
 */
function google_map_field_latlon_validate($element, $form, &$form_state) {
  if (!is_numeric($element['#value']) && !empty($element['#value'])) {
    $field = implode('][', $element['#array_parents']);
    form_set_error($field, t('Invalid value - @title', array('@title' => $element['#title'])));
  }
}

/**
 * Implements hook_theme().
 */
function google_map_field_theme($existing, $type, $theme, $path) {
  if ($type == 'module') {
    return array(
      'google_map_field' => array(
        'variables' => array(
          'name' => NULL,
          'lat' => NULL,
          'lng' => NULL,
          'lzoom' => NULL,
        ),
        'template' => 'google-map-field',
        'path' => drupal_get_path('module', 'google_map_field') . '/theme',
      ),
    );
  }
  return array();
}

/**
 * Helper function to add the Google Maps API.
 */
function google_map_field_add_maps_api() {
  if (variable_get('google_map_field_apikey', '') != '') {
    $element = array(
      '#type' => 'markup',
      '#markup' => '<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false&key=' . variable_get('google_map_field_apikey', '') . '"></script>',
    );
    drupal_add_html_head($element, 'google_maps_api');
  }
  else {
    drupal_add_js('//maps.googleapis.com/maps/api/js?sensor=false', 'external');
  }
}

/**
 * Helper function to return all fields created on the system
 * of the google map field type.
 */
function google_map_field_get_fields() {
  $types = array_keys(google_map_field_field_info());
  $fields = array();
  foreach (field_info_fields() as $field) {
    if (in_array($field['type'], $types)) {
      $fields[] = $field;
    }
  }
  return $fields;
}
