<?php

/**
 *  @file
 *  Provide main module for custom functionality.
 */

  module_load_include('inc', 'custom','custom.pages');
  module_load_include('inc', 'custom','custom.form');
  module_load_include('inc', 'custom','custom');
  module_load_include('inc', 'custom','custom.block');


/**
 * Implements hook_menu_alter().
 */
function custom_menu_alter(&$items) {
  $items['node']['access callback'] = FALSE;
}

